[font]
size = 14.0

[font.bold]
family = "ShureTechMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "ShureTechMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "ShureTechMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "ShureTechMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "None"
key = "Up"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "None"
key = "Down"
mods = "Control|Alt"

[terminal.shell]
args = ["--login", "--command=tmux attach; or tmux new -s work"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.8
blur = true
resize_increments = true
option_as_alt = "Both"

[terminal]
